### PR TITLE
FAQ, join us, testimonial section added. Also the partner with us section at footer is added

### LINKED ISSUE #34: Add testimonials Section
Add testimonial Section on Home Page Before Footer

### PR DESCRIPTION
**Pull request by castorNova2**
FAQ section, and testimonial section added. Changed the build tool from CRA to Vite. Also, "partner with us" card is added. Events, resources, mission section added. Responsiveness added. Also, a loader is added. Also, a custom scroll bar is added. CSS files are converted into CSS modules to make CSS style scope local (reduces the global import bug)

Issue resolved: #34

Screenshots: 
image
image
image
image
image
image
image
image
image
image
image
image
image

### CODE REVIEW

**Comment by Codefamily1** [comment]
Make the testimonials design shown below, and revisit the Join Us section. 

image

**Comment by castorNova2** [comment]
> Make the testimonials design shown below, and revisit the Join Us section. 
> 
> image

OK, and what it means "revisit the join us section", like redesign it?

**Comment by castorNova2** [comment]
@Codefamily1 testimonial section changed as per requested

**Comment by Codefamily1** [comment]
make it responsive

**Comment by castorNova2** [comment]
> make it responsive

done

**Pull request merged**
